#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct  1 11:24:34 2024

@author: earnestt1234
"""

import os
import shutil
import tempfile
import warnings

from colorama import Fore, Style
import nibabel as nib
import numpy as np

from atstaging.config import get
from atstaging.preprocessing.execute import execute
from atstaging.preprocessing.conversion import ecat_to_nifti, run_dcm2niix
from atstaging.preprocessing.reorient import reorient_image
from atstaging.preprocessing.segmentation import compute_regional_statistics_MUSE
from atstaging.preprocessing.smoothing import iterative_smoothing

def _registration_outputs(prefix):
    outputs = {
        # files created by PET-to-MRI coregistration (rigid)
        'pet2mri_transform': prefix + "0GenericAffine.mat",
        'rigidregistered': prefix + "Warped.nii.gz",
        'inv_rigidregistered': prefix + "InverseWarped.nii.gz",

        # PET-to-MNI when MRI-to-MNI is linear
        'pet2mni_linear': prefix + 'FullTransformLinear.mat',

        # PET-to-MNI when MRI-to-MNI is nonlinear,
        'pet2mni_nonlinear': prefix + 'FullTransformNonLinear.nii.gz',

        # Other files not generated by ANTs, but from this pipeline        
        'origsuvr': prefix + 'OrigSUVR.nii.gz',
        'petbrainmask': prefix + 'BrainMaskPETSpace.nii.gz',
        'petsegmentation': prefix + 'SegementationPETSpace.nii.gz',
        'petbrain': prefix + 'PETBrain.nii.gz',
        'petregistered': prefix + 'PETRegistered.nii.gz'
        }
    return outputs

def _copy_outputs(prefix, out_registered=None, out_rigid_reg=None,
                  out_suvr=None, out_pet2mni=None, out_petbrain=None,
                  pet2mni_is_linear=False):

    outputs = _registration_outputs(prefix)
    registered = outputs['petregistered']
    rigid_reg = outputs['rigidregistered']
    suvr = outputs['origsuvr']
    pet2mni = outputs['pet2mni_linear'] if pet2mni_is_linear else outputs['pet2mni_nonlinear']
    petbrain = outputs['petbrain']

    if os.path.isfile(registered) and out_registered is not None:
        shutil.move(registered, out_registered)

    if os.path.isfile(rigid_reg) and out_rigid_reg is not None:
        shutil.move(rigid_reg, out_rigid_reg)

    if os.path.isfile(suvr) and out_suvr is not None:
        shutil.move(suvr, out_suvr)

    if os.path.isfile(pet2mni) and out_pet2mni is not None:
        shutil.move(pet2mni, out_pet2mni)

    if os.path.isfile(petbrain) and out_petbrain is not None:
        shutil.move(petbrain, out_petbrain)

def _get_img_format(pet):
    if os.path.isdir(pet):
        return 'DICOM'
    elif pet.endswith('.v'):
        return 'ECAT'
    elif pet.endswith('.nii.gz'):
        return 'NIFTI'
    elif pet.endswith('.nii'):
        return 'NIFTI_UNCOMPRESSED'
    else:
        raise ValueError(f'Unrecognized type for {os.path.basename(pet)}')
    
def _get_shape_dict(img):
    nii = nib.load(img)
    shape = nii.shape
    output = {f'Dim{i}': s for i, s in enumerate(shape) if i <= 3}
    if len(shape) == 3:
        output['Dim3'] = None
    return output

def _is_dynamic(pet):
    nii = nib.load(pet)
    shape = nii.shape
    if len(shape) == 3:
        return False
    elif len(shape) == 4:
        return True
    else:
        raise ValueError(f'Unrecognized shape for determining dynamic image: {shape}')

def prepare_registration_pet(pet, out_nifti=None,
                             out_realign=None, out_average=None,
                             out_final=None, target_fwhm=(10, 10, 10)):
    outputs = [out_nifti, out_realign, out_average, out_final]
    if all([x is None for x in outputs]):
        raise ValueError('At least one output must be specified for PET pre-registration.')
    
    INFO = {
        'Source': pet
    }

    with tempfile.TemporaryDirectory() as WORKINGDIR:

        # variable to track the image as it progresses through different steps
        TEMPIMAGE_NAME = '_temp_image'
        TEMPIMAGE = os.path.join(WORKINGDIR, TEMPIMAGE_NAME + '.nii.gz')

        # covert to NIFTI
        img_fmt = _get_img_format(pet)
        INFO['ImageFormat'] = img_fmt
        print()
        print(f'>>> Detected image format: {img_fmt}')

        if img_fmt == 'DICOM':
            print()
            print('>>> Running DICOM to NIFTI conversion...')
            print('- - -')
            run_dcm2niix(pet, WORKINGDIR, TEMPIMAGE_NAME)
            print('- - -')
        elif img_fmt == 'ECAT':
            print()
            print('>>> Running ECAT to NIFTI conversion...')
            print('- - -')
            ecat_to_nifti(pet, TEMPIMAGE)
            print('- - -')
        elif img_fmt in ['NIFTI_UNCOMPRESSED', 'NIFTI']:
            print()
            print('>>> Creating compressed NIFTI image')
            print('- - -')
            nii = nib.load(pet)
            nib.save(nii, TEMPIMAGE)
            print('- - -')

        # reorient, and then save out_nifti if requested
        print()
        print('>>> Running image reorientation...')
        reorient_image(TEMPIMAGE, 'RPI')

        if out_nifti is not None:
            shutil.copy(TEMPIMAGE, out_nifti)

        # realignment
        INFO['IsDynamic'] = _is_dynamic(TEMPIMAGE)
        INFO.update(_get_shape_dict(TEMPIMAGE))
        if _is_dynamic(TEMPIMAGE):
            print()
            print('>>> Running MCFLIRT for realignment of PET frames...')
            print('- - -')
            run_mcflirt(TEMPIMAGE, TEMPIMAGE)
            print('- - -')
            INFO['MCFLIRTApplied'] = True
        else:
            print('>>> Image is not dynamic; skipping realignment.')
            INFO['MCFLIRTApplied'] = False

        if out_realign:
            shutil.copy(TEMPIMAGE, out_realign)

        # averaging
        if _is_dynamic(TEMPIMAGE):
            print('>>> Averaging image across frames...')
            print('- - -')
            nii = nib.load(TEMPIMAGE)
            data = nii.get_fdata().mean(axis=3)
            newimg = nib.Nifti1Image(dataobj=data, affine=nii.affine, header=nii.header)
            nib.save(newimg, TEMPIMAGE)
            print('- - -')
            INFO['AverageApplied'] = True
        else:
            print('>>> Image is not dynamic; skipping averaging.')
            INFO['AverageApplied'] = False

        if out_average:
            shutil.copy(TEMPIMAGE, out_average)

        # smoothing
        if target_fwhm is None:
            print()
            print('>>> No target FWHM supplied; not smoothing.')
        else:
            print()
            print(f'>>> Applying iterative smoothing algorithm to target: {target_fwhm} mm FWHM...')
            print('- - -')
            smoothstats = iterative_smoothing(TEMPIMAGE, TEMPIMAGE, target_fwhm=target_fwhm,
                                              start_fwhm=(0, 0, 0), stepsize=0.5,
                                              tolerance=0.5, max_iterations=75,
                                              automask=True, difMAD=True, verbose=True)
            INFO.update(smoothstats)
            print('- - -')

        if out_final:
            shutil.copy(TEMPIMAGE, out_final)

        print()
        print('PET pre-registration steps completed.')

        return INFO

def register_pet_image(pet, t1, brainmask, mri2mni_transform, suvr_reference_mask=None, muse_segmentation=None,
                       mni_brain=None, out_registered=None, out_suvr=None, out_rigid_reg=None, out_pet2mni=None,
                       out_petbrain=None, out_regional_suvrs=None):
    
    # check if outputs being created
    outputs = [out_registered, out_rigid_reg, out_pet2mni, out_petbrain, out_suvr, out_regional_suvrs]
    if all(x is None for x in outputs):
        warnings.warn(RuntimeWarning('MRI registration: no outputs selected, exiting!'))
        return
    
    # initialize dict with information about this process
    INFO = {}

    # check mri2mni_transform type
    mni_transform_is_linear = mri2mni_transform.lower().endswith('.mat')

    # MAIN
    with tempfile.TemporaryDirectory() as WORKINGDIR:

        print()
        print(f'>>> Created temporary working directory: {WORKINGDIR}')

        # variables
        ANTSPATH = get('ants')
        C3D_AFFINE_TOOL = get('c3d_affine_tool')
        FSLPATH = get('fsl')
        FLIRT = os.path.join(FSLPATH, 'bin', 'flirt')
        PREFIX = os.path.join(WORKINGDIR, '_temp_output')
        OUTNAMES = _registration_outputs(PREFIX)
        REFERENCE = mni_brain if mni_brain is not None else get('mni152_brain')

        # software
        ants_applytransforms = os.path.join(ANTSPATH, 'antsApplyTransforms')
        ants_imagemath = os.path.join(ANTSPATH, 'ImageMath')

        print()
        print(Fore.BLUE + Style.BRIGHT + 'PET Registration')
        print('~~~~~'  + Style.RESET_ALL)

        # rigid registration

        # ----> Registration
        rigidregisted = OUTNAMES['rigidregistered']
        pet2mri_transform = OUTNAMES['pet2mri_transform']

        command = [
            FLIRT,
            '-in', pet,
            '-ref', t1,
            '-out', rigidregisted,
            '-omat', pet2mri_transform,
            '-dof', '6',
            '-cost', 'mutualinfo',
            '-v'
            ]

        print()
        print('>>> Running rigid registration of PET to MRI:')
        print('    ' + Fore.YELLOW + ' '.join(command) + Style.RESET_ALL)
        print('- - -')
        execute(command)
        print('- - -')

        # ----> Covert FSL affine to ANTs
        command = [
            C3D_AFFINE_TOOL,
            '-ref', t1,
            '-src', pet,
            pet2mri_transform,
            '-fsl2ras',
            '-oitk', pet2mri_transform
        ]

        print()
        print('>>> Converting PET2MRI linear transformation matrix from FSL to ANTs format:')
        print('    ' + Fore.YELLOW + ' '.join(command) + Style.RESET_ALL)
        print('- - -')
        execute(command)
        print('- - -')

        # compute SUVR
        rigidregisted = OUTNAMES['rigidregistered']
        working_pet_image = pet
        suvr = OUTNAMES['origsuvr']
        if suvr_reference_mask is not None:
            print()
            print(f'>>> Using {suvr_reference_mask} to compuete an SUVR.')
            img = nib.load(rigidregisted)
            mask = nib.load(suvr_reference_mask)
            img_data = img.get_fdata()
            mask_data = np.isclose(mask.get_fdata(), 1.0).astype(float)
            mask_applied = np.where(mask_data == 1, img_data, 0.)
            sum_img_data = mask_applied.sum()
            n_voxels_in_mask = mask_data.sum()
            ref_uptake = float(sum_img_data / n_voxels_in_mask)
            INFO['ReferenceUptake'] = ref_uptake

            print(f'>>> Reference uptake value: {ref_uptake}')
            nii = nib.load(pet)
            data = nii.get_fdata()
            print(f'>>> Range before SUVR normalization: {float(data.min()), float(data.max())}')
            INFO['PreSUVRMin'] = float(data.min())
            INFO['PreSUVRMax'] = float(data.max())

            data /= ref_uptake
            print(f'>>> Range after SUVR normalization: {float(data.min()), float(data.max())}')
            INFO['PostSUVRMin'] = float(data.min())
            INFO['PostSUVRMax'] = float(data.max())
            
            data = np.where(data < 0, 0, data)
            print(f'>>> Range after negative removal: {float(data.min()), float(data.max())}')
            INFO['ZeroNegMin'] = float(data.min())
            INFO['ZeroNegMax'] = float(data.max())

            newimg = nib.Nifti1Image(dataobj=data, affine=nii.affine)
            nib.save(newimg, suvr)
            working_pet_image = suvr

        # skullstrip the PET image
        pet2mri_transform = OUTNAMES['pet2mri_transform']
        petbrain = OUTNAMES['petbrain']
        petbrainmask = OUTNAMES['petbrainmask']
        command = [
            ants_applytransforms,
            '-d', '3',
            '-i', brainmask,
            '-r', working_pet_image,
            '-o', petbrainmask,
            '-t', f"[{pet2mri_transform},1]",
            '-n', 'NearestNeighbor',
            '-v'
            ]

        print()
        print('>>> Moving MRI brain mask to PET space:')
        print('    ' + Fore.YELLOW + ' '.join(command) + Style.RESET_ALL)
        print('- - -')
        execute(command)
        print('- - -')

        command = [ants_imagemath, '3', petbrain, 'm', petbrainmask, working_pet_image]

        print()
        print('>>> Skullstripping the PET image:')
        print('    ' + Fore.YELLOW + ' '.join(command) + Style.RESET_ALL)
        print('- - -')
        execute(command)
        print('- - -')

        # get regional SUVRs for PET image
        petsegmentation = OUTNAMES['petsegmentation']
        if muse_segmentation is not None:
            command = [
                ants_applytransforms,
                '-d', '3',
                '-i', muse_segmentation,
                '-r', working_pet_image,
                '-o', petsegmentation,
                '-t', f"[{pet2mri_transform},1]",
                '-n', 'NearestNeighbor',
                '-v'
                ]
            
            print()
            print('>>> Moving T1 MUSE segmentation to PET space:')
            print('    ' + Fore.YELLOW + ' '.join(command) + Style.RESET_ALL)
            print('- - -')
            execute(command)
            print('- - -')

            print()
            print('>>> Computing regional statistics from segmentation in PET space:')
            print('- - -')
            regional_suvrs = compute_regional_statistics_MUSE(img=working_pet_image, segmentaion=petsegmentation)
            if out_regional_suvrs is not None:
                regional_suvrs.to_csv(out_regional_suvrs, index=False)
            print('- - -')

        # combined transform
        key = 'pet2mni_linear' if mni_transform_is_linear else 'pet2mni_nonlinear'
        pet2mni_transform = OUTNAMES[key]
        output_argument_value = f'Linear[{pet2mni_transform},0]' if mni_transform_is_linear else f'[{pet2mni_transform},1]' 
        command = [
            ants_applytransforms,
            '-d', '3',
            '-i', working_pet_image,
            '-r', REFERENCE,
            '-t', mri2mni_transform, pet2mri_transform,
            '-o', output_argument_value,
            '-v', '1']

        print()
        print('>>> Combining the transformation (PET -> T1 + T1 -> MNI):')
        print('    ' + Fore.YELLOW + ' '.join(command) + Style.RESET_ALL)
        print('- - -')
        execute(command)
        print('- - -')

        # apply combined transform
        final = OUTNAMES['petregistered']
        command = [
            ants_applytransforms,
            '-d', '3',
            '-i', petbrain,
            '-r', REFERENCE,
            '-t', pet2mni_transform,
            '-o', final,
            '-v', '1']

        print()
        print('>>> Moving PET brain image to MNI space:')
        print('    ' + Fore.YELLOW + ' '.join(command) + Style.RESET_ALL)
        print('- - -')
        execute(command)
        print('- - -')

        # move output files
        print()
        print('>>> Copying outputs to selected destinations. ')
        _copy_outputs(PREFIX, out_registered=out_registered, out_suvr=out_suvr,
                      out_pet2mni=out_pet2mni, out_rigid_reg=out_rigid_reg,
                      out_petbrain=out_petbrain, pet2mni_is_linear=mni_transform_is_linear)

        # cleanup
        # this is removing all the temporary images created in the PREFIX directory
        # the user-specified outputs should already be moved
        print()
        print('>>> Removing temporary files.')
        print('- - -')
        for key, value in OUTNAMES.items():
            msg = 'NOT FOUND'
            if os.path.exists(value):
                msg = 'REMOVED'
                os.remove(value)
            print(f'  - "{key}": {value} [{msg}]')
        print('- - -')

        print('Completed!')

        return INFO

def run_mcflirt(inimg, outimg):

    FSLDIR = get('fsl')
    mcflirt = os.path.join(FSLDIR, 'bin', 'mcflirt')
    command = [mcflirt,
               '-in', inimg,
               '-out', outimg,
               '-report',
               '-stages', '4']
    execute(command, env={'FSLOUTPUTTYPE': 'NIFTI_GZ'})
